### ISSUE TITLE
Feature request: accept array or List<string> in RemoveProfanity()

### ISSUE THREAD

**Issue by twwilliams** [stephenhaunts/ProfanityDetector#12]
It would be nice if RemoveProfanity() could accept an array or List<string> the same way that AddProfanity() does.

**Comment by stephenhaunts** [comment]
Sounds reasonable. Leave it with me.

Steve

**Comment by stephenhaunts** [comment]
Hi. I have added two method overrides to RemoveProfanity. One takes a List<string> and the other string[].

I have updated the published NuGet package to 0.1.8.

Thanks for the feature request :-)

Steve

**Comment by twwilliams** [comment]
Thank you very much.
