### ISSUE TITLE
Why .NET Standard 2.1?

### ISSUE THREAD

**Issue by halomademeapc** [stephenhaunts/ProfanityDetector#2]
Hi,
I'm wanting to use this on a project that uses a CMS built on .NET Framework.  I was just wondering why you having it targeting .NET Standard 2.1 as this means [it is incompatible with .NET Framework](https://github.com/dotnet/standard/blob/master/docs/versions.md#net-standard-versions).  I took a quick look through the code and nothing immediately jumped out to me as using C# 8 language features or .NET Standard 2.1 interfaces.  Is there any reason you can't compile targeting the much more compatible .NET Standard 2.0?

**Comment by stephenhaunts** [comment]
Hi, to be honest there is no reason why it can’t support net standard 2. I will change the version on the project and push and republish the NuGet package. I will try and get this done tomorrow. I just got a little excited with the .net core 3 release 🤓

**Comment by stephenhaunts** [comment]
Hi, I have checked in the changes to move the project file down to .NET Standard 2.0. I have also published the NuGet package, version 0.1.2.
