### ISSUE TITLE
The reverse-Scunthorpe problem

### ISSUE THREAD

**Issue by aaron-bond** [stephenhaunts/ProfanityDetector#7]
Hi there,

Assuming I have a use-case where I want the profanity in Scunthorpe to be detected - is that something I can do here? I've had a look through the public methods and can't find anything appropriate. Any suggestions?

Thanks!

**Comment by stephenhaunts** [comment]
Do you mean, if you had the sentence "I like in a town called Scunthorpe," that the profanity detector would flag 'Scunthorpe' because it contains the 'C' word?

**Comment by aaron-bond** [comment]
@stephenhaunts yep, exactly. Is that a thing?

**Comment by aaron-bond** [comment]
@stephenhaunts if it's not something the package already does, would you be open to a PR with a new public method specifically to find cases like `Scunthorpe`?

**Comment by stephenhaunts** [comment]
Yeah, I would be up for that. What's the use-case for doing that case? Do you have a specific example?

The original intention was to solve the Scunthorpe problem as a lot of other profanity filters don't resolve it.

**Comment by aaron-bond** [comment]
In my case it's a tool that generates random Ids for users; I don't want to end up with `ass123` accidentally so this tool can give me a retry case.

**Comment by stephenhaunts** [comment]
ah, interesting, I hadn't considered that :-)

**Comment by willemaster** [comment]
Hi @stephenhaunts, thanks for this. We have exactly the same issue. Unless you're working on this already, I can submit a PR?

**Comment by aaron-bond** [comment]
My PR has been merged already; the method is `ContainsProfanity`. I think @stephenhaunts is planning to release the nuget package with the update.

**Comment by stephenhaunts** [comment]
Hi, I will try and the NuGet packages updated and uploaded tonight (UK time). Things have been a little slow as still homeschooling 2 kids. Oh, the joy... :-)

**Comment by stephenhaunts** [comment]
Hi, I have uploaded the latest nuget package, v0.1.6

Steve

**Comment by stephenhaunts** [comment]
Merged pull request with request feature and re-released nuget package with latest feature.

**Comment by willemaster** [comment]
Amazing, thanks both and good luck with the homeschooling :)

**Comment by aaron-bond** [comment]
Thank you kindly @stephenhaunts
